esphome:
  name: we-motion-1
  friendly_name: WeMotion 1
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp8266:
  board: esp01_1m

# Enable logging
logger:

web_server:
  
# Enable Home Assistant API
api:
  encryption:
    key: ":)"

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.157
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

binary_sensor:
  - platform: gpio
    pin: GPIO5
    name: "Radar"
    device_class: motion
    filters:
      - delayed_off: 2s
                 
captive_portal: